# Generated by Django 5.0.3 on 2024-03-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="Projects/")),
                ("link", models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name="Portfolio",
        ),
    ]
