# Generated by Django 5.0.3 on 2024-03-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_projects_delete_portfolio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="image",
            field=models.ImageField(upload_to="project/"),
        ),
    ]
